### ISSUE TITLE
Minimize Exposure Bias of Seq2Seq Models in Joint Entity and Relation Extraction

### ISSUE THREAD

**Issue by Faiz-07** [WindChimeRan/OpenJERE#4]
Hello sir,
I run the code of this paper but error occur (FileNotFoundError: [Errno 2] No such file or directory: 'data/chinese/seq2umt\\word_vocab.json').
word_vocab.json file is missing please send this file.
thanks

**Comment by 404-N0T-Found** [comment]
老哥  这个问题解决了吗？

**Comment by 32209056** [comment]
请问data/chinese/seq2umt\word_vocab.json').解决了吗
